### ISSUE TITLE
Failed to parse time string

### ISSUE THREAD

**Issue by sluchznak** [Tigrov/yii2-pgsql#2]
Hello.
Your package is awesome!
But I found bug when try to execute migration
```
Exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (NULL::timestamp without time zone) at position 0 (N): The timezone could not be found in the database'
```

**Comment by Tigrov** [comment]
Hi, thanks for the report.
The bug in the base class `\yii\db\pgsql\Schema` too.
I'll send them a pull request to fix it.

**Comment by Tigrov** [comment]
Please check the fix, if everything fine I'll make new release.
