### ISSUE TITLE
DateTime в формах

### ISSUE THREAD

**Issue by ManasAtabaev** [Tigrov/yii2-pgsql#3]
Каким образом можно использовать обьект DateTime в формах?

`<?= $form->field($model, 'from_date')->widget(\yii\jui\DatePicker::classname(), [
    'dateFormat' => 'yyyy-MM-dd',
]) ?>`
Ошибка
`Object of class DateTime could not be converted to string`

**Comment by Tigrov** [comment]
It requires to convert the `\DateTime` object to `string`.
You can try this way:
```php
<?= $form->field($model, 'from_date')->textInput(['value' => $model->from_date->format('Y-m-d')])->widget(\yii\jui\DatePicker::className()) ?>
```
or if `$model->from_date` is not always `\DateTime`
```php
<?= $form->field($model, 'from_date')->textInput(['value' => \Yii::$app->formatter->asDate($model->from_date, 'yyyy-MM-dd')])->widget(\yii\jui\DatePicker::className()) ?>
```

**Comment by Tigrov** [comment]
Fixed in Yii 2.0.14
