### ISSUE TITLE
Composite Type in materialized view

### ISSUE THREAD

**Issue by kr0lik** [Tigrov/yii2-pgsql#4]
Если создать материализованную вьюху(да и наверно просто вьюху) на основе таблицы с массивом композитного поля(some_type[]) - то при формировании модели это поле получается в виде строки.

**Comment by Tigrov** [comment]
It seems the reason is in Postgres' Views. The Views don't have information about array dimension of an array type.
I made a solution but it will work with one-dimension array types only.

Please try the fix and write about the result.

**Comment by kr0lik** [comment]
Composite types works fine. But jsonb[](maybe json[] too) formed as an array even if in compositeMap set 'jsonb' => 'object' - in view its still array. For table all works fine.

**Comment by Tigrov** [comment]
json and jsonb are native PostgreSQL types and the extension converts them in associative arrays.

You can convert json types (associative arrays) to `object` in your ActiveRecord model using `$model::afterFind()`.

Or you can extend or fork the extension and change the line 
https://github.com/Tigrov/yii2-pgsql/blob/master/src/ColumnSchema.php#L171
from
`return json_decode($value, true);`
to
`return json_decode($value);`

**Comment by kr0lik** [comment]
Оh, sorry, i was mistake. Json really converts to associative arrays everywhere. Thanks for help!
