### ISSUE TITLE
Обновление Yii2 2.0.14

### ISSUE THREAD

**Issue by Stokwel** [Tigrov/yii2-pgsql#7]
Обновление сломало работу расширения с ошибкой:
`Declaration of tigrov\\pgsql\\QueryBuilder::batchInsert($table, $columns, $rows) should be compatible with yii\\db\\pgsql\\QueryBuilder::batchInsert($table, $columns, $rows, &$params = Array)`

**Comment by Tigrov** [comment]
Fixed. Thanks.
